[package]
name = "wgfont"
version = "0.1.0"
edition = "2024"

[dependencies]
fontdb = "0.23.0"
fontdue = "0.9.3"
fxhash = "0.2.1"
guillotiere = "0.6.2"
log = "0.4.28"
mini-moka = "0.10.3"
quick_cache = "0.6.18"
wgpu = "27.0.1"

[dev-dependencies]
image = "0.25.8"

[lints.clippy]
unwrap-used = "warn"
too-many-arguments = "allow"
